apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: horizontalpodautoscalers.autoscaling.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/kubernetes/pull/72635"
spec:
  group: autoscaling.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
              properties:
                name:
                  type: string
  scope: Namespaced
  names:
    plural: horizontalpodautoscalers
    singular: horizontalpodautoscaler
    kind: HorizontalPodAutoscaler
    shortNames:
      - hpa
