apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: default  # Replace with your namespace if different
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust the storage size as per your requirements and available resources
  storageClassName: <your-storage-class>  # Replace with the appropriate storage class name
